### ISSUE TITLE
[🧩] Phase 01 : Error & Loading

### ISSUE THREAD

**Issue by elisebeall** [mi-voz-mi-voto/mi-voz-mi-voto#12]
Add an Error component to handle fetch GET & POST errors.
Add a Loading component to handle slow requests & responses.

**Comment by ivonne-hernandez** [comment]
![loading](https://user-images.githubusercontent.com/86989161/152706792-bb7595df-17a0-4053-bec5-3cf482f9157d.png)

**Comment by ivonne-hernandez** [comment]
For the Error component:
![005-mute-3](https://user-images.githubusercontent.com/86989161/152707407-556de3e2-d121-497c-87e8-b5c29b64da9e.png)
![006-mute-4](https://user-images.githubusercontent.com/86989161/152707411-db121d49-8fca-41f2-92a6-525d4d32ba6f.png)
